// G-Diffuser — port entry point.
// Slice 4c: libultraship init + resource pipeline. Creates the engine Context (window, audio,
// input, resource manager), mounts the extracted asset archive, registers resource factories,
// and binds the game's asset symbols to runtime .o2r data. The game-loop coroutine lands next.

#include "ship/Context.h"
#include "ship/resource/ResourceManager.h"
#include "resource/ResourceFactories.h"

#include <memory>
#include <string>
#include <vector>

// Generated by tools/gen_asset_bindings.py — fills every asset pointer from the .o2r.
extern "C" void GDiffuser_LoadAllAssets(void);

int main(int argc, char** argv) {
    const std::vector<std::string> archivePaths = { "generic.o2r" };

    auto ctx = Ship::Context::CreateInstance("G-Diffuser", "gdiffuser", "gdiffuser.cfg.json",
                                             archivePaths);
    if (ctx == nullptr) {
        return 1;
    }

    GDiffuser::RegisterResourceFactories(ctx->GetResourceManager()->GetResourceLoader());
    GDiffuser_LoadAllAssets();

    // TODO (4c): run the decomp game loop wrapped in a coroutine driven by libultraship's frames.
    return 0;
}
