#!/usr/bin/env python3
"""G-Diffuser asset binding generator (Slice 4c / R2).

Reads the decomp's asset metadata YAMLs and produces:
  1. Shadow headers  port/gen/assets/us/rev0/<category>.h  — each asset symbol declared as a
     POINTER (extern u16* D_xxx;) instead of Torch's typed array (extern u16 D_xxx[];). These
     shadow the Torch-generated headers via include-path priority, so the game code's
     `#include ASSET_HEADER(...)` picks up the pointer declarations.
  2. port/gen/AssetBindings.c — defines every asset pointer and a GDiffuser_LoadAllAssets()
     that fills each from the .o2r at startup via GDiffuser_LoadAsset("<category>/<symbol>").

This is the core of the resource refactor: it turns 1,779 compiled asset symbols into
runtime resource loads, without compiling any asset data as C.
"""
import glob
import os
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_YAML_DIR = os.path.join(REPO, "decomp", "assets", "yaml", "us", "rev0")
GEN_HEADER_DIR = os.path.join(REPO, "port", "gen", "assets", "us", "rev0")
BINDING_C = os.path.join(REPO, "port", "gen", "AssetBindings.c")

os.makedirs(GEN_HEADER_DIR, exist_ok=True)

defs, loads = [], []
total = 0

for path in sorted(glob.glob(os.path.join(ASSET_YAML_DIR, "*.yaml"))):
    category = os.path.splitext(os.path.basename(path))[0]
    with open(path) as f:
        data = yaml.safe_load(f) or {}

    guard = "GEN_" + category.upper() + "_H"
    hdr = ["#ifndef " + guard, "#define " + guard, '#include "gfx.h"', ""]

    for key, val in data.items():
        if not isinstance(val, dict) or str(key).startswith(":"):
            continue
        sym = val.get("symbol", key)
        ctype = val.get("ctype", "u8")
        hdr.append("extern {}* {};".format(ctype, sym))
        if isinstance(val.get("width"), int):
            hdr.append("#define _{}_WIDTH 0x{:X}".format(sym, val["width"]))
        if isinstance(val.get("height"), int):
            hdr.append("#define _{}_HEIGHT 0x{:X}".format(sym, val["height"]))
        defs.append("{}* {} = NULL;".format(ctype, sym))
        loads.append('    {} = ({}*)GDiffuser_LoadAsset("{}/{}");'.format(sym, ctype, category, sym))
        total += 1

    hdr += ["", "#endif"]
    with open(os.path.join(GEN_HEADER_DIR, category + ".h"), "w") as f:
        f.write("\n".join(hdr) + "\n")

with open(BINDING_C, "w") as f:
    f.write("// AUTO-GENERATED by tools/gen_asset_bindings.py (R2). Do not edit by hand.\n")
    f.write('#include "global.h"\n\n')
    f.write("// Implemented in the port (C++): fetch a loaded asset's data pointer from the .o2r.\n")
    f.write("extern void* GDiffuser_LoadAsset(const char* key);\n\n")
    f.write("\n".join(defs))
    f.write("\n\nvoid GDiffuser_LoadAllAssets(void) {\n")
    f.write("\n".join(loads))
    f.write("\n}\n")

print("R2: generated {} asset bindings".format(total))
print("  headers -> {}".format(GEN_HEADER_DIR))
print("  binding -> {}".format(BINDING_C))
