#!/usr/bin/env python3
"""G-Diffuser link-stub generator (Slice 4c / R4+R5 bring-up).

Reads the undefined symbols from a top-build.log and emits port/gen/LinkStubs.c defining each
so the executable LINKS. Data-like symbols (segment/overlay/framebuffer linker markers, globals,
microcode blobs) become 1-byte placeholders; the rest become no-op functions returning 0.

These are PLACEHOLDERS to reach a linked binary. Real implementations (segment system, overlay
loader, save/leo/mfs, arena, audio microcode) are R5/R6 — verified on a real desktop runtime.
"""
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(REPO, "top-build.log")
OUT = os.path.join(REPO, "port", "gen", "LinkStubs.c")

# Symbols we implement for real elsewhere (shims.c, decomp_port.c) — never stub these.
EXCLUDE = {
    "Arena_Allocate", "Arena_StartInit", "Arena_DefaultStartInit", "Arena_EndInit",
}

syms = set()
with open(LOG, encoding="utf-8", errors="ignore") as f:
    for line in f:
        m = re.search(r"undefined symbol: (\S+)", line)
        if m:
            s = m.group(1).strip()
            if s not in EXCLUDE:
                syms.add(s)

# Heuristic: linker-marker / global / blob symbols are DATA; everything else is a function.
DATA_RE = re.compile(
    r"(_VRAM(_END)?$|_ROM_(START|END)$|_BSS_(START|END)$|_DATA_(START|END|SIZE)$"
    r"|_TEXT_(START|END)$|_RODATA_END$|^ovl_i|^framebuffer|^D_[0-9A-Fa-f]|^g[A-Z]|^s[A-Z]"
    r"|^a[A-Z]|fifo(Text|Data)(Start|End)$|^rspboot|^leoBootID$|qnan|^unk_|osViMode|^osTvType$)"
)

data = sorted(s for s in syms if DATA_RE.search(s))
funcs = sorted(s for s in syms if not DATA_RE.search(s))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// AUTO-GENERATED by tools/gen_link_stubs.py. Placeholder defs for unported symbols.\n")
    f.write("// Data = 1-byte buffers; functions = no-op returning 0. Real impls: R5/R6 (desktop).\n\n")
    for s in data:
        f.write("unsigned char {}[1];\n".format(s))
    f.write("\n")
    for s in funcs:
        f.write("long {}() {{ return 0; }}\n".format(s))

print("link stubs: {} data, {} funcs -> {}".format(len(data), len(funcs), OUT))
