#!/usr/bin/env python3
"""G-Diffuser asset binding generator (Slice 4c / R2).

Emits port/gen/AssetBindings.c, which DEFINES every decomp asset symbol as a (placeholder)
array of its declared C type. This keeps the symbols as arrays — matching Torch's
`extern <ctype> <sym>[];` headers — so:
  * the symbols are defined (no undefined-symbol link errors), and
  * their addresses are compile-time constants, so the game's STATIC tables / display lists
    that reference assets still compile (a runtime pointer can't be a static initializer).

Torch's generated headers (with their _WIDTH/_HEIGHT/_COMPRESSED_SIZE #defines) are used as-is;
no shadow headers are produced.

NOTE: arrays are placeholders ([1]). Filling them with real asset data from the .o2r at the
right sizes is R6 work (needs runtime on a real display). GDiffuser_LoadAllAssets() is the hook.
"""
import glob
import os
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_YAML_DIR = os.path.join(REPO, "decomp", "assets", "yaml", "us", "rev0")
BINDING_C = os.path.join(REPO, "port", "gen", "AssetBindings.c")

os.makedirs(os.path.dirname(BINDING_C), exist_ok=True)

defs = []
total = 0
for path in sorted(glob.glob(os.path.join(ASSET_YAML_DIR, "*.yaml"))):
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    for key, val in data.items():
        if not isinstance(val, dict) or str(key).startswith(":"):
            continue
        sym = val.get("symbol", key)
        ctype = val.get("ctype", "u8")
        defs.append("{} {}[1];".format(ctype, sym))
        total += 1

with open(BINDING_C, "w") as f:
    f.write("// AUTO-GENERATED by tools/gen_asset_bindings.py (R2). Do not edit by hand.\n")
    f.write("// Placeholder array definitions for every decomp asset symbol (kept as arrays so\n")
    f.write("// static asset references compile). Real size + .o2r data load = R6.\n")
    f.write('#include "global.h"\n\n')
    f.write("\n".join(defs))
    f.write("\n\nvoid GDiffuser_LoadAllAssets(void) {\n")
    f.write("    // TODO (R6, needs runtime): load each asset's data from the .o2r into these\n")
    f.write("    // buffers at correct sizes (via the resource system).\n")
    f.write("}\n")

print("R2: defined {} asset symbols -> {}".format(total, BINDING_C))
